name: Actions Workflow

#on: [push]
on:
  #Trigger the workflow from an external source
  #https://api.github.com/repos/gcarmo-ciandt/github-actions/test/dispatches
  #HEADERS
  #Accept application/vnd.github.everest-preview+json
  #Content-Type application/json
  repository_dispatch:
  #schedule:
  #  - cron: "0/5 * * * *"
  #  - cron: "0/6 * * * *"
  pull_request:
    types: [opened, reopened]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: |
          pwd
          ls
      - name: Checkout
        uses: actions/checkout@v2
      - name: List Files
        run: |
          pwd
          ls -a
      - name: Simple JS Actions
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: Carmo
      - name: Log Greeting Time
        run: echo "${{ steps.greet.outputs.time }}"